### ISSUE TITLE
Console not showing on error page 

### ISSUE THREAD

**Issue by Ben-Owen-3183** [rails/web-console#331]
On newest master the error console does not show in the error page anymore.

No errros in browser console

No errors in rails terminal.

**Comment by rafaelfranca** [comment]
This is probably because of Rack 3 incompatibilities. The console isn't rendered because it thinks the content-type isn't html.

**Comment by JoeDupuis** [comment]
It looks like [this has been fixed already](https://github.com/rails/web-console/commit/69a756e2e468ab5448d4e3d0fa1615a6c78cde7d#diff-2292e10a3263a2c7d9e5d4cdf2b746951c97ff526c6160feafaac773addbbedeL55-R55).

Switching my Gemfile to `gem "web-console", github: "rails/web-console", branch: "master"` brings it back.

Can we cut a release?

**Comment by rafaelfranca** [comment]
That doesn't fix the issue. It actually make it worse since now that code doesn't work with Rack 2.x. That is the problem OP was talking about. With `gem "web-console", github: "rails/web-console", branch: "master"` on the gemfile of an existing Rails application, the console doesn't work anymore. So if I do a new release it will break existing applications.

**Comment by JoeDupuis** [comment]
Oh! My bad :man_facepalming:  I misread and assumed OP had the same issue I had, running Rails edge with older console not the reverse.

I'll try to take a look at it this week if no one gets to it first.
